import Sidebar from "@/components/Sidebar";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <div className="m-6 rounded-2xl overflow-hidden border border-white">
          <div className="flex h-[calc(100vh-3rem)]">
            <Sidebar />
            <main className="flex-1 overflow-y-auto p-8 bg-black/40 backdrop-blur-md border-l border-yellow-400">
              <div className="max-w-4xl mx-auto w-full">
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}



